baseurl = "https://mashareko.tk/"
title = "Masha Reko - Apprenticeship Blog"
copyright = "Copyright &copy; 2018 - Masha Reko"
canonifyurls = true
theme = "kiera"

paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

[author]
    name = "Masha Reko"
    github = "https://github.hc.ag/mreko"
    linkedin = "https://rs.linkedin.com/in/masareko"
    facebook = "https://www.facebook.com/masha.reko"

[params]
    tagline = "What we have to learn to do, we learn by doing. (Aristotle)"

[[menu.main]]
    name = "Home" 
    weight = 10 
    url = "https://mashareko.tk/"
[[menu.main]]
    name = "Posts"
    weight = 20
    url = "/posts/"


