baseurl = "https://masha-reko.tk/"
title = "Masha Reko - Apprenticeship Blog"
copyright = "Copyright &copy; 2018 - Masha Reko"
canonifyurls = true
theme = "kiera"

paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

[author]
    name = "Masha Reko"
    github = "mmreko"
    linkedin = "masareko"
    facebook = "masha.reko"

[params]
    tagline = "What we have to learn to do, we learn by doing. (Aristotle)"

[[menu.main]]
    name = "Home" 
    weight = 10 
    url = "https://masha-reko.tk/"
[[menu.main]]
    name = "Posts"
    weight = 20
    url = "/posts/"


